config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'service', to: 'pages#service'
  get 'news', to: 'pages#news'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def service
  end

  def news
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="sticky-nav">
  <div class="nav-content">
    <%= image_tag 'logo.png', alt: 'Company Logo', class: 'nav-logo' %>
    <ul class="nav-links">
      <li><%= link_to '首页', root_path, class: 'btn' %></li>
      <li><%= link_to '关于我们', about_path, class: 'btn' %></li>
      <li><%= link_to '服务展示', service_path, class: 'btn' %></li>
      <li><%= link_to '新闻中心', news_path, class: 'btn' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GewuTech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>关于我们</h1>
<p>格物智能科技有限公司介绍。</p>

app/views/pages/home.html.erb
<div class="content" data-controller="animation">
  <section class="hidden">
    <h1>格物智能科技有限公司</h1>
    <p>欢迎来到公司首页！</p>
    <%= image_tag 'home_image.png', alt: 'Home Image', class: 'home-image' %>
  </section>

  <section class="hidden">
    <h2>关于我们</h2>
    <p>简单介绍公司资质。</p>
    <%= image_tag 'about_image.png', alt: 'About Image', class: 'about-image' %>
  </section>

  <section class="hidden">
    <h2>服务展示</h2>
    <p>简单介绍我们是做什么的</p>
    <%= image_tag 'service_image.png', alt: 'Service Image', class: 'service-image' %>
  </section>
</div>

app/views/pages/news.html.erb
<h1>新闻中心</h1>
<p>关于公司的最新新闻。</p>

app/views/pages/service.html.erb
<h1>服务展示</h1>
<p>关于格物智能科技有限公司能做到什么。</p>